import { useState, useEffect } from "react";
import Sidebar from "../../components/Sidebar";
import { useNavigate } from "react-router-dom";

function TheorySchedulePage() {
    const navigate = useNavigate();
    
    const [activeTab, setActiveTab] = useState("manual"); // "auto", "manual" ili "schedule"
    const [autoGeneratedSuccess, setAutoGeneratedSuccess] = useState(false);

    const [professors, setProfessors] = useState([]);
    const [domains, setDomains] = useState([]);
    const [candidates, setCandidates] = useState([]);
    
    // manual
    const [theoryDate, setTheoryDate] = useState("");
    const [theoryStartTime, setTheoryStartTime] = useState("10:00");
    const [theoryEndTime, setTheoryEndTime] = useState("11:30");
    const [capacity, setCapacity] = useState(20);
    const [selectedProfessorId, setSelectedProfessorId] = useState("");
    const [selectedDomainId, setSelectedDomainId] = useState("");
    const [selectedCandidateIds, setSelectedCandidateIds] = useState([]);
    const [searchCandidateQuery, setSearchCandidateQuery] = useState("");

    // auto-generate
    const [autoStartDate, setAutoStartDate] = useState("");
    const [autoEndDate, setAutoEndDate] = useState("");
    const [autoCapacity, setAutoCapacity] = useState(20);
    const [autoDomainId, setAutoDomainId] = useState("");

    const [message, setMessage] = useState({ text: "", isError: false });

    useEffect(() => {
        fetch("http://localhost:8080/user/professors")
            .then((res) => res.json())
            .then((data) => setProfessors(Array.isArray(data) ? data : []))
            .catch((err) => console.error("Error loading professors:", err));

        fetch("http://localhost:8080/api/theory-classes/domains") 
            .then((res) => res.json())
            .then((data) => {
                console.log("Loaded domains from backend:", data);
                setDomains(Array.isArray(data) ? data : []);
            })
            .catch((err) => console.error("Error loading domains:", err));

        fetch("http://localhost:8080/candidate/all") 
            .then((res) => res.json())
            .then((data) => {
                if (Array.isArray(data)) {
                    const theoryCandidates = data.filter(c => c.status === "THEORY" || c.candidateStatus === "THEORY");
                    setCandidates(theoryCandidates);
                } else {
                    setCandidates([]);
                }
            })
            .catch((err) => console.error("Error loading candidates:", err));
    }, []);

    // --- MANUEL LOGIC ---
    const handleToggleCandidate = (id) => {
        if (selectedCandidateIds.includes(id)) {
            setSelectedCandidateIds(selectedCandidateIds.filter(cId => cId !== id));
        } else {
            setSelectedCandidateIds([...selectedCandidateIds, id]);
        }
    };

    const handleSelectAllCandidates = () => {
        const filtered = candidates.filter(c => 
            `${c.firstName || ""} ${c.lastName || ""}`.toLowerCase().includes(searchCandidateQuery.toLowerCase())
        );
        const filteredIds = filtered.map(c => c.id);
        setSelectedCandidateIds([...new Set([...selectedCandidateIds, ...filteredIds])]);
    };

    const handleDeselectAllCandidates = () => {
        setSelectedCandidateIds([]);
    };

    const handleManualSubmit = (e) => {
        e.preventDefault();
        setMessage({ text: "", isError: false });

        if (!theoryDate || !selectedProfessorId || !selectedDomainId) {
            setMessage({ text: "Please fill in all required fields (Date, Professor, Domain).", isError: true });
            return;
        }

        const createDto = {
            theoryDate: theoryDate,
            theoryStartTime: `${theoryStartTime}:00`,
            theoryEndTime: `${theoryEndTime}:00`,
            capacity: parseInt(capacity),
            professorId: parseInt(selectedProfessorId),
            domainId: parseInt(selectedDomainId),
            candidateIds: selectedCandidateIds
        };

        fetch("http://localhost:8080/api/theory-classes", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(createDto)
        })
        .then(async (res) => {
            const rawText = await res.text();
            if (!res.ok) {
                try {
                    const parsed = JSON.parse(rawText);
                    throw new Error(parsed.message || "Error creating class.");
                } catch {
                    throw new Error(rawText || "Error on server.");
                }
            }
            return rawText;
        })
        .then(() => {
            setMessage({ text: "Class created successfully!", isError: false });
            setTheoryDate("");
            setSelectedCandidateIds([]);
            setSelectedProfessorId("");
            setSelectedDomainId("");
        })
        .catch(err => {
            if (err.message.includes("Professor is not available")) {
                setMessage({ text: "Professor is not available in this period!", isError: true });
            } else if (err.message.includes("Professor already has class")) {
                setMessage({ text: "Professor already has a class scheduled in the selected time slot!", isError: true });
            } else {
                setMessage({ text: err.message, isError: true });
            }
        });
    };

    // --- AUTO-GENERATE LOGIC ---
    const handleAutoGenerateSubmit = (e) => {
        e.preventDefault();
        setMessage({ text: "", isError: false });

        if (!autoStartDate || !autoEndDate || !autoDomainId) {
            setMessage({ text: "Please fill in all required fields (Date Range, Domain).", isError: true });
            return;
        }

        const autoDto = {
            startDate: autoStartDate,
            endDate: autoEndDate,
            defaultCapacity: parseInt(autoCapacity),
            domainId: parseInt(autoDomainId)
        };

        fetch("http://localhost:8080/api/theory-classes/auto-generate", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(autoDto)
        })
        .then(async (res) => {
            const rawText = await res.text();
            if (!res.ok) {
                try {
                    const parsed = JSON.parse(rawText);
                    throw new Error(parsed.message || "Error.");
                } catch {
                    throw new Error(rawText || "Error on server.");
                }
            }
            return rawText;
        })
        .then(() => {
            setAutoGeneratedSuccess(true);
        })
        .catch(err => {
            setMessage({ text: err.message, isError: true });
        });
    };

    const filteredCandidates = candidates.filter(c => {
        const fullName = `${c.firstName || ""} ${c.lastName || ""}`.toLowerCase();
        return fullName.includes(searchCandidateQuery.toLowerCase());
    });

    const activeProfessor = professors.find(p => String(p.id) === String(selectedProfessorId));
    const activeDomain = domains.find(d => String(d.domainId) === String(selectedDomainId));

    const logout = () => {
        localStorage.removeItem("user");
        window.location.href = "/";
    };

    return (
        <div style={styles.container}>
            <Sidebar
                buttons={[
                    { label: "Candidates", onClick: () => navigate("/admin/candidates") },
                    { label: "Professors", onClick: () => navigate("/admin/professors") },
                    { label: "Instructors", onClick: () => navigate("/admin/instructors") },
                    { label: "Vehicles", onClick: () => navigate("/admin/vehicles") },
                    { label: "Theory Schedule", onClick: () => navigate("/admin/theory-schedule") },
                    { label: "Requests", onClick: () => navigate("/admin/requests") },
                ]}
                logout={logout}
            />

            <div style={styles.content}>
                <div style={styles.wireframeBox}>
                    <h1 style={styles.mainTitle}>Create Theory Schedule</h1>

                    <div style={styles.tabContainer}>
                        <button 
                            type="button"
                            style={{...styles.tabBtn, ...(activeTab === "auto" ? styles.activeTabBtn : {})}}
                            onClick={() => { setActiveTab("auto"); setAutoGeneratedSuccess(false); setMessage({text:"", isError:false}); }}
                        >
                            Auto Generate
                        </button>
                        <button 
                            type="button"
                            style={{...styles.tabBtn, ...(activeTab === "manual" ? styles.activeTabBtn : {})}}
                            onClick={() => { setActiveTab("manual"); setMessage({text:"", isError:false}); }}
                        >
                            Manual Create
                        </button>
                        <button 
                            type="button"
                            style={{...styles.tabBtn, ...(activeTab === "schedule" ? styles.activeTabBtn : {})}}
                            onClick={() => navigate("/admin/theory-schedule-view")}
                        >
                            Schedule View
                        </button>
                    </div>

                    {message.text && (
                        <div style={{
                            ...styles.statusMessage,
                            backgroundColor: message.isError ? "#f8d7da" : "#d4edda",
                            color: message.isError ? "#721c24" : "#155724"
                        }}>
                            {message.text}
                        </div>
                    )}

                    {activeTab === "auto" && !autoGeneratedSuccess && (
                        <form onSubmit={handleAutoGenerateSubmit} style={styles.formWidth}>
                            <div style={styles.autoRow}>
                                <div style={styles.textLeftBlock}>
                                    <div style={styles.wireframeLabelFrame}>You can create schedule automatically.</div>
                                </div>
                                <button type="submit" style={styles.wireframeActionBtn}>GENERATE SCHEDULE</button>
                            </div>

                            <div style={{...styles.sectionBlock, marginTop: "20px"}}>
                                <h3 style={styles.sectionTitle}>Auto-generation Parameters:</h3>
                                <div style={styles.flexInputsRow}>
                                    <input type="date" value={autoStartDate} onChange={(e) => setAutoStartDate(e.target.value)} style={styles.wireframeInput} />
                                    <input type="date" value={autoEndDate} onChange={(e) => setAutoEndDate(e.target.value)} style={styles.wireframeInput} />
                                    
                                    <select value={autoDomainId} onChange={(e) => setAutoDomainId(e.target.value)} style={styles.wireframeSelect}>
                                        <option value="">Select Domain</option>
                                        {domains.map((d, index) => (
                                            <option key={d.domainId || index} value={String(d.domainId)}>
                                                {d.domainOrderNumber || index + 1}. {d.domainName}
                                            </option>
                                        ))}
                                    </select>
                                    <input type="number" placeholder="Capacity" value={autoCapacity} onChange={(e) => setAutoCapacity(e.target.value)} style={{...styles.wireframeInput, width: "90px"}} />
                                </div>
                            </div>

                            <div style={{...styles.autoRow, marginTop: "20px"}}>
                                <div style={styles.textLeftBlock}>
                                    <div style={styles.wireframeLabelFrame}>Or you can create schedule manually.</div>
                                </div>
                                <button type="button" onClick={() => setActiveTab("manual")} style={styles.wireframeActionBtn}>CREATE MANUALLY</button>
                            </div>
                        </form>
                    )}

                    {activeTab === "auto" && autoGeneratedSuccess && (
                        <div style={styles.successWrapperBox}>
                            <div style={styles.autoRow}>
                                <div style={styles.textLeftBlock}>
                                    <div style={styles.wireframeLabelFrame}>You can create schedule automatically.</div>
                                </div>
                                <button disabled style={{...styles.wireframeActionBtn, opacity: 0.6}}>GENERATE SCHEDULE</button>
                            </div>
                            <div style={{...styles.autoRow, marginTop: "15px", marginBottom: "30px"}}>
                                <div style={styles.textLeftBlock}>
                                    <div style={styles.wireframeLabelFrame}>Or you can create schedule manually.</div>
                                </div>
                                <button type="button" onClick={() => setActiveTab("manual")} style={styles.wireframeActionBtn}>CREATE MANUALLY</button>
                            </div>

                            <div style={styles.popupSuccessAlert}>
                                <p style={{fontSize: "22px", marginBottom: "20px"}}>Schedule is generated successfully!</p>
                                <button onClick={() => navigate("/admin/theory-schedule-view")} style={styles.viewScheduleBtn}>VIEW SCHEDULE</button>
                            </div>
                        </div>
                    )}

                    {activeTab === "manual" && (
                        <form onSubmit={handleManualSubmit} style={styles.formWidth}>
                            
                            {/* BLOK 1: Date & Time Slot */}
                            <div style={styles.sectionBlock}>
                                <div style={styles.inlineSectionRow}>
                                    <span style={styles.blockLabel}>Date & Time Slot</span>
                                    <div style={styles.rightInputsGroup}>
                                        <input type="date" value={theoryDate} onChange={(e) => setTheoryDate(e.target.value)} style={styles.wireframeInput} />
                                        <input type="time" value={theoryStartTime} onChange={(e) => setTheoryStartTime(e.target.value)} style={{...styles.wireframeInput, width: "90px"}} />
                                        <span style={{fontSize: "14px"}}>to</span>
                                        <input type="time" value={theoryEndTime} onChange={(e) => setTheoryEndTime(e.target.value)} style={{...styles.wireframeInput, width: "90px"}} />
                                        <input type="number" placeholder="Cap." value={capacity} onChange={(e) => setCapacity(e.target.value)} style={{...styles.wireframeInput, width: "60px"}} title="Capacity" />
                                    </div>
                                </div>
                            </div>

                            <div style={styles.sectionBlock}>
                                <div style={styles.inlineSectionRow}>
                                    <span style={styles.blockLabel}>Professor & Domain</span>
                                    <div style={styles.rightInputsGroup}>
                                        
                                        <select value={selectedProfessorId} onChange={(e) => setSelectedProfessorId(e.target.value)} style={styles.wireframeSelect}>
                                            <option value="">Select Professor</option>
                                            {professors.map(p => (
                                                <option key={p.id} value={String(p.id)}>{p.firstName} {p.lastName}</option>
                                            ))}
                                        </select>

                                        <select value={selectedDomainId} onChange={(e) => setSelectedDomainId(e.target.value)} style={styles.wireframeSelect}>
                                            <option value="">Select Domain</option>
                                            {domains.map((d, index) => (
                                                <option key={d.domainId || index} value={String(d.domainId)}>
                                                    {d.domainOrderNumber || index + 1}. {d.domainName}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div style={styles.sectionBlock}>
                                <span style={{...styles.blockLabel, display: "block", marginBottom: "15px"}}>Candidates</span>
                                
                                <div style={styles.candidateActionHeader}>
                                    <div style={styles.searchContainer}>
                                        <span style={{marginRight: "5px"}}>🔍</span>
                                        <input 
                                            type="text" 
                                            placeholder="search" 
                                            value={searchCandidateQuery}
                                            onChange={(e) => setSearchCandidateQuery(e.target.value)}
                                            style={styles.searchInsideInput}
                                        />
                                    </div>
                                    <div style={{gap: "10px", display: "flex"}}>
                                        <button type="button" onClick={handleSelectAllCandidates} style={styles.miniWireframeBtn}>Select All</button>
                                        <button type="button" onClick={handleDeselectAllCandidates} style={styles.miniWireframeBtn}>Deselect all</button>
                                    </div>
                                </div>

                                <div style={styles.candidatesGrid}>
                                    {filteredCandidates.map(c => {
                                        const isChecked = selectedCandidateIds.includes(c.id);
                                        return (
                                            <div 
                                                key={c.id} 
                                                style={{...styles.candidateCard, backgroundColor: isChecked ? "#e6f4ea" : "#ffffff"}}
                                                onClick={() => handleToggleCandidate(c.id)}
                                            >
                                                <input 
                                                    type="checkbox" 
                                                    checked={isChecked}
                                                    onChange={() => {}} 
                                                    style={{marginRight: "8px", pointerEvents: "none"}} 
                                                />
                                                <div style={{fontSize: "12px", lineHeight: "1.2"}}>
                                                    <strong>{c.firstName} {c.lastName}</strong>
                                                    <div style={{color: "#666", fontSize: "11px"}}>ID: #{c.id}</div>
                                                </div>
                                            </div>
                                        );
                                    })}
                                    {filteredCandidates.length === 0 && (
                                        <div style={{gridColumn: "1/-1", textAlign: "center", color: "#888", fontSize: "14px", padding: "10px"}}>
                                            Nema pronađenih kandidata.
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div style={styles.sectionBlock}>
                                <span style={{...styles.blockLabel, display: "block", marginBottom: "10px"}}>Summary</span>
                                <div style={styles.summaryContentRow}>
                                    <div style={styles.summaryTextLines}>
                                        <div><strong>Date:</strong> {theoryDate || "_______"} ({theoryStartTime} - {theoryEndTime})</div>
                                        <div><strong>Professor:</strong> {activeProfessor ? `${activeProfessor.firstName} ${activeProfessor.lastName}` : "_______"}</div>
                                        <div><strong>Lesson:</strong> {activeDomain ? activeDomain.domainName : "_______"}</div>
                                        <div><strong>Candidates:</strong> {selectedCandidateIds.length} selektovano (Maks. {capacity})</div>
                                    </div>
                                    <div style={styles.summaryActionsRight}>
                                        <button 
                                            type="button" 
                                            onClick={() => { 
                                                handleDeselectAllCandidates(); 
                                                setTheoryDate(""); 
                                                setSelectedProfessorId(""); 
                                                setSelectedDomainId(""); 
                                                setTheoryStartTime("10:00");
                                                setTheoryEndTime("11:30");
                                            }} 
                                            style={styles.bottomWireframeBtn}
                                        >
                                            Reset Form
                                        </button>
                                        <button type="submit" style={{...styles.bottomWireframeBtn, backgroundColor: "#9cc2cb"}}>Create Class</button>
                                    </div>
                                </div>
                            </div>

                        </form>
                    )}
                </div>
            </div>
        </div>
    );
}

const styles = {
    container: { display: "flex", minHeight: "100vh" },
    content: { flex: 1, padding: "30px", backgroundColor: "#ffffff", fontFamily: '"Arial", sans-serif', display: "flex", justifyContent: "center" },
    wireframeBox: { border: "2px solid #333333", padding: "30px 40px", width: "100%", maxWidth: "850px", display: "flex", flexDirection: "column", alignItems: "center", backgroundColor: "#ffffff", boxSizing: "border-box" },
    mainTitle: { fontSize: "32px", fontWeight: "normal", color: "#222", marginBottom: "25px", marginTop: "0", textAlign: "center" },
    tabContainer: { display: "flex", border: "2px solid #333333", borderRadius: "6px", marginBottom: "25px", overflow: "hidden", width: "360px" },
    tabBtn: { flex: 1, padding: "10px", border: "none", backgroundColor: "#ffffff", cursor: "pointer", fontSize: "14px", fontWeight: "bold", fontFamily: "inherit", borderRight: "1px solid #333", textAlign: "center" },
    activeTabBtn: { backgroundColor: "#9cc2cb", color: "#000000" },
    formWidth: { width: "100%" },
    statusMessage: { width: "100%", padding: "10px", borderRadius: "6px", textAlign: "center", fontSize: "14px", fontWeight: "bold", marginBottom: "15px", border: "1px solid currentColor" },
    autoRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", gap: "20px" },
    textLeftBlock: { flex: 1 },
    wireframeLabelFrame: { border: "2px solid #333333", padding: "10px 15px", fontSize: "16px", minWidth: "250px" },
    wireframeActionBtn: { padding: "10px 20px", border: "2px solid #333333", borderRadius: "6px", backgroundColor: "#ffffff", cursor: "pointer", fontSize: "14px", fontWeight: "bold", fontFamily: "inherit" },
    flexInputsRow: { display: "flex", gap: "10px", flexWrap: "wrap", marginTop: "10px" },
    sectionTitle: { margin: "0 0 10px 0", fontSize: "16px" },
    sectionBlock: { border: "2px solid #333333", padding: "15px 20px", width: "100%", marginBottom: "15px", boxSizing: "border-box" },
    inlineSectionRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", flexWrap: "wrap", gap: "15px" },
    blockLabel: { fontSize: "18px", fontWeight: "bold", color: "#222" },
    rightInputsGroup: { display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap" },
    wireframeInput: { padding: "6px 10px", border: "2px solid #333333", borderRadius: "4px", fontSize: "14px", fontFamily: "inherit" },
    wireframeSelect: { padding: "6px 10px", border: "2px solid #333333", borderRadius: "4px", fontSize: "14px", fontFamily: "inherit", minWidth: "140px" },
    candidateActionHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "12px" },
    searchContainer: { display: "flex", alignItems: "center", border: "2px solid #333333", padding: "4px 10px", borderRadius: "15px", width: "200px" },
    searchInsideInput: { border: "none", outline: "none", fontSize: "14px", width: "100%", fontFamily: "inherit" },
    miniWireframeBtn: { padding: "4px 12px", border: "2px solid #333333", borderRadius: "6px", backgroundColor: "#ffffff", fontSize: "12px", cursor: "pointer", fontFamily: "inherit" },
    candidatesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: "10px", maxHeight: "150px", overflowY: "auto", border: "1px solid #ccc", padding: "10px", backgroundColor: "#fafafa" },
    candidateCard: { display: "flex", alignItems: "center", border: "2px solid #333333", padding: "8px", borderRadius: "4px", cursor: "pointer", userSelect: "none" },
    summaryContentRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", width: "100%", flexWrap: "wrap", gap: "15px" },
    summaryTextLines: { fontSize: "14px", lineHeight: "1.6", display: "flex", flexDirection: "column", gap: "4px" },
    summaryActionsRight: { display: "flex", gap: "12px" },
    bottomWireframeBtn: { padding: "8px 16px", border: "2px solid #333333", borderRadius: "6px", backgroundColor: "#ffffff", fontSize: "15px", fontWeight: "bold", cursor: "pointer", fontFamily: "inherit" },
    successWrapperBox: { width: "100%", display: "flex", flexDirection: "column", alignItems: "center" },
    popupSuccessAlert: { width: "80%", border: "2px solid #333333", padding: "30px", marginTop: "20px", textAlign: "center", backgroundColor: "#ffffff" },
    viewScheduleBtn: { padding: "8px 20px", border: "2px solid #333333", backgroundColor: "#ffffff", fontSize: "16px", cursor: "pointer", fontWeight: "bold", fontFamily: "inherit" }
};

export default TheorySchedulePage;